# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsimple < Formula
  desc "Terminal-first DNSimple client (TUI + CLI)"
  homepage "https://github.com/dorkitude/simple"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkitude/simple/releases/download/v0.2.0/dnsimple_0.2.0_darwin_amd64.tar.gz"
      sha256 "6176c3807987e2a35b5268e9930e0a8b61add7553c6ac702a7cd52f875e8e0eb"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkitude/simple/releases/download/v0.2.0/dnsimple_0.2.0_darwin_arm64.tar.gz"
      sha256 "f55aa6e84afe936f7c90140529cba340053b4224228a2ba7ab23768d18ebb392"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.2.0/dnsimple_0.2.0_linux_amd64.tar.gz"
      sha256 "9dd834b9dfae57be1980344d90e1324cde831afcef03fe3282911a74503732dd"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.2.0/dnsimple_0.2.0_linux_arm64.tar.gz"
      sha256 "b71f0df82a7d3924f776b7230922b399c387c138bf7e8bd529bec516de3f8471"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  test do
    assert_match "DNSimple", shell_output("#{bin}/dnsimple --help")
  end
end
