# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsimple < Formula
  desc "Terminal-first DNSimple client (TUI + CLI)"
  homepage "https://github.com/dorkitude/simple"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkitude/simple/releases/download/v0.3.0/dnsimple_0.3.0_darwin_amd64.tar.gz"
      sha256 "b8895b21894bc5cd93685d7dd2cfdec07aad995299d4dc7f1a1413bcf16bc939"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkitude/simple/releases/download/v0.3.0/dnsimple_0.3.0_darwin_arm64.tar.gz"
      sha256 "838e7e44c67e72afb3b5cc32cb3f39f51e4bda61a09eaf460cbfbbea3f3d2189"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.3.0/dnsimple_0.3.0_linux_amd64.tar.gz"
      sha256 "2e98c78b1428ca9d2faf1757f4d207952d7ad7e7b14c40e1f42301aa34b60b4c"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.3.0/dnsimple_0.3.0_linux_arm64.tar.gz"
      sha256 "f366e864c5bc8b3f3c555a171756078409f59f085b9f069bfe5af936fd881696"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  test do
    assert_match "DNSimple", shell_output("#{bin}/dnsimple --help")
  end
end
