# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsimple < Formula
  desc "Terminal-first DNSimple client (TUI + CLI)"
  homepage "https://github.com/dorkitude/simple"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkitude/simple/releases/download/v0.1.0/dnsimple_0.1.0_darwin_amd64.tar.gz"
      sha256 "9769d0855ca9edde5fd4a569b47a94bd74d95c76c11e2a6921cf0423b0f0f3cd"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkitude/simple/releases/download/v0.1.0/dnsimple_0.1.0_darwin_arm64.tar.gz"
      sha256 "4b28037751ed3fa760a0e1af1390552ab6f7650e16c838d8070064264a54d46c"

      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.1.0/dnsimple_0.1.0_linux_amd64.tar.gz"
      sha256 "b371deec78a6c8b03a256e45c6678d9db43bcd469d5f31aa3d0e8f35fece97b8"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkitude/simple/releases/download/v0.1.0/dnsimple_0.1.0_linux_arm64.tar.gz"
      sha256 "5ab2bf43fc307ea5528daa10941af7b87adc03868bceefb970832ae72e874ce5"
      define_method(:install) do
        bin.install "dnsimple"
        bin.install_symlink "dnsimple" => "simple"
        bin.install_symlink "dnsimple" => "dnsimplectl"
      end
    end
  end

  test do
    assert_match "DNSimple", shell_output("#{bin}/dnsimple --help")
  end
end
